[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_pass

# ---  para evitar el error de "sobrecarga" ---
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 1200
limit_time_real = 2400
max_cron_threads = 2
workers = 0

#Le dan a Odoo más tiempo (20-40 minutos) para procesar el 
#backup antes de que el servidor "se rinda"
